CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    phone VARCHAR(40),
    password_hash VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE table_qr_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    token VARCHAR(120) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_table_qr_tokens_table FOREIGN KEY (table_id) REFERENCES restaurant_tables(id)
);

CREATE TABLE tabs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    table_id BIGINT,
    customer_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    opened_by_user_id BIGINT,
    closed_by_user_id BIGINT,
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    notes VARCHAR(1000),
    CONSTRAINT fk_tabs_table FOREIGN KEY (table_id) REFERENCES restaurant_tables(id),
    CONSTRAINT fk_tabs_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_tabs_opened_by FOREIGN KEY (opened_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_tabs_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_tabs_status CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

ALTER TABLE orders ADD COLUMN tab_id BIGINT;
ALTER TABLE orders ADD CONSTRAINT fk_orders_tab FOREIGN KEY (tab_id) REFERENCES tabs(id);

CREATE TABLE order_item_customizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL,
    customization_type VARCHAR(20) NOT NULL,
    item_name VARCHAR(160) NOT NULL,
    price_delta DECIMAL(12,2) NOT NULL DEFAULT 0,
    addon_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_item_customizations_item FOREIGN KEY (order_item_id) REFERENCES order_items(id),
    CONSTRAINT fk_order_item_customizations_addon FOREIGN KEY (addon_id) REFERENCES addons(id),
    CONSTRAINT chk_order_item_customization_type CHECK (customization_type IN ('ADD', 'REMOVE', 'NOTE'))
);

CREATE TABLE product_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE,
    quantity DECIMAL(12,3),
    minimum_quantity DECIMAL(12,3),
    track_inventory BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_inventory_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT chk_product_inventory_quantity CHECK (quantity IS NULL OR quantity >= 0)
);

CREATE TABLE cash_registers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'CLOSED',
    opening_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
    closing_balance DECIMAL(12,2),
    opened_by_user_id BIGINT,
    closed_by_user_id BIGINT,
    opened_at TIMESTAMP,
    closed_at TIMESTAMP,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cash_registers_opened_by FOREIGN KEY (opened_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_cash_registers_closed_by FOREIGN KEY (closed_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_cash_registers_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    cash_register_id BIGINT,
    method VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    amount DECIMAL(12,2) NOT NULL,
    transaction_reference VARCHAR(160),
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_payments_cash_register FOREIGN KEY (cash_register_id) REFERENCES cash_registers(id),
    CONSTRAINT chk_payments_amount CHECK (amount > 0),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'APPROVED', 'REFUSED', 'CANCELLED', 'REFUNDED'))
);

CREATE TABLE cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_register_id BIGINT NOT NULL,
    movement_type VARCHAR(20) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    order_id BIGINT,
    created_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cash_movements_register FOREIGN KEY (cash_register_id) REFERENCES cash_registers(id),
    CONSTRAINT fk_cash_movements_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_cash_movements_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_cash_movements_type CHECK (movement_type IN ('OPENING', 'SALE', 'WITHDRAWAL', 'SUPPLY', 'CLOSING', 'REFUND')),
    CONSTRAINT chk_cash_movements_amount CHECK (amount > 0)
);

CREATE TABLE couriers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    phone VARCHAR(40) NOT NULL UNIQUE,
    document VARCHAR(30),
    vehicle_type VARCHAR(40),
    vehicle_plate VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    courier_id BIGINT,
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING_ASSIGNMENT',
    assigned_at TIMESTAMP,
    dispatched_at TIMESTAMP,
    delivered_at TIMESTAMP,
    delivery_notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_deliveries_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_deliveries_courier FOREIGN KEY (courier_id) REFERENCES couriers(id),
    CONSTRAINT chk_deliveries_status CHECK (status IN ('WAITING_ASSIGNMENT', 'ASSIGNED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED'))
);

CREATE TABLE service_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT,
    order_id BIGINT,
    request_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    description VARCHAR(1000),
    handled_by_user_id BIGINT,
    handled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_service_requests_table FOREIGN KEY (table_id) REFERENCES restaurant_tables(id),
    CONSTRAINT fk_service_requests_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_service_requests_handled_by FOREIGN KEY (handled_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_service_requests_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED'))
);

CREATE TABLE kitchen_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    priority INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    station VARCHAR(80),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kitchen_queue_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT chk_kitchen_queue_status CHECK (status IN ('WAITING', 'IN_PREPARATION', 'READY', 'CANCELLED'))
);

CREATE TABLE print_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    document_type VARCHAR(40) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    printed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_print_queue_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT chk_print_queue_status CHECK (status IN ('PENDING', 'PROCESSING', 'PRINTED', 'FAILED', 'CANCELLED'))
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    order_id BIGINT,
    channel VARCHAR(30) NOT NULL,
    recipient VARCHAR(180) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    provider_reference VARCHAR(160),
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_notifications_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT chk_notifications_status CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'CANCELLED'))
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    action VARCHAR(40) NOT NULL,
    previous_data TEXT,
    new_data TEXT,
    ip_address VARCHAR(80),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE system_settings (
    setting_key VARCHAR(120) PRIMARY KEY,
    setting_value TEXT,
    updated_by_user_id BIGINT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_system_settings_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE INDEX idx_products_category_available ON products(category_id, available);
CREATE INDEX idx_addresses_customer ON addresses(customer_id);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_status_history_order ON order_status_history(order_id, created_at);
CREATE INDEX idx_users_active ON users(active);
CREATE INDEX idx_table_qr_tokens_table_active ON table_qr_tokens(table_id, active);
CREATE INDEX idx_tabs_status_table ON tabs(status, table_id);
CREATE INDEX idx_order_item_customizations_item ON order_item_customizations(order_item_id);
CREATE INDEX idx_payments_order_status ON payments(order_id, status);
CREATE INDEX idx_cash_movements_register_created ON cash_movements(cash_register_id, created_at);
CREATE INDEX idx_deliveries_courier_status ON deliveries(courier_id, status);
CREATE INDEX idx_service_requests_status_created ON service_requests(status, created_at);
CREATE INDEX idx_kitchen_queue_status_priority ON kitchen_queue(status, priority, created_at);
CREATE INDEX idx_print_queue_status_created ON print_queue(status, created_at);
CREATE INDEX idx_notifications_status_created ON notifications(status, created_at);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id, created_at);
