ALTER TABLE customers ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE products ADD COLUMN unavailable_reason VARCHAR(300);
ALTER TABLE tabs ADD COLUMN service_type VARCHAR(20) NOT NULL DEFAULT 'TABLE';
ALTER TABLE tabs ADD COLUMN subtotal DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE tabs ADD COLUMN total DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE tabs ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE tab_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(160) NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    quantity INTEGER NOT NULL,
    extras_snapshot VARCHAR(1000),
    removals_snapshot VARCHAR(1000),
    notes VARCHAR(1000),
    line_total DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    cancelled_at TIMESTAMP,
    cancellation_reason VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tab_items_tab FOREIGN KEY (tab_id) REFERENCES tabs(id),
    CONSTRAINT fk_tab_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT chk_tab_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_tab_items_status CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

CREATE TABLE tab_item_customizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_item_id BIGINT NOT NULL,
    customization_type VARCHAR(20) NOT NULL,
    item_name VARCHAR(160) NOT NULL,
    price_delta DECIMAL(12,2) NOT NULL DEFAULT 0,
    addon_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tab_item_customizations_item FOREIGN KEY (tab_item_id) REFERENCES tab_items(id),
    CONSTRAINT fk_tab_item_customizations_addon FOREIGN KEY (addon_id) REFERENCES addons(id),
    CONSTRAINT chk_tab_item_customization_type CHECK (customization_type IN ('ADD', 'REMOVE', 'NOTE'))
);

ALTER TABLE payments ALTER COLUMN order_id DROP NOT NULL;
ALTER TABLE payments ADD COLUMN tab_id BIGINT;
ALTER TABLE payments ADD CONSTRAINT fk_payments_tab FOREIGN KEY (tab_id) REFERENCES tabs(id);
CREATE INDEX idx_tab_items_tab_status ON tab_items(tab_id, status);
CREATE INDEX idx_tabs_status_updated ON tabs(status, updated_at);
